<a href="https://colab.research.google.com/github/Mazi-star/LABWORK1/blob/main/LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Создаем свой уникальный датасет
data = {
    'Товар': ['Смартфон', 'Ноутбук', 'Планшет', 'Смартфон', 'Наушники', 'Телевизор', 'Ноутбук', 'Монитор'],
    'Категория': ['Электроника', 'Компьютеры', 'Электроника', 'Электроника', 'Аудио', 'Электроника', 'Компьютеры', 'Компьютеры'],
    'Цена': [50000, 120000, 35000, 50000, 15000, 80000, 120000, np.nan],
    'Возраст_модели_мес': [12, 6, 18, 12, 3, 24, 6, 10],
    'Гарантия_мес': [24, 12, 12, 24, 6, 36, 12, 12]
}

df = pd.DataFrame(data)

print("Исходный DataFrame:")
display(df)

Исходный DataFrame:

       Товар    Категория      Цена  Возраст_модели_мес  Гарантия_мес
0   Смартфон  Электроника   50000.0                  12            24
1    Ноутбук   Компьютеры  120000.0                   6            12
2    Планшет  Электроника   35000.0                  18            12
3   Смартфон  Электроника   50000.0                  12            24
4   Наушники        Аудио   15000.0                   3             6
5  Телевизор  Электроника   80000.0                  24            36
6    Ноутбук   Компьютеры  120000.0                   6            12
7    Монитор   Компьютеры       NaN                  10            12

In [ ]:
print("--- Метод head(3) (Первые 3 строки) ---")
display(df.head(3))

print("\n--- Метод tail(2) (Последние 2 строки) ---")
display(df.tail(2))

print("\n--- Свойство shape (Размерность) ---")
print(f"Строк: {df.shape[0]}, Столбцов: {df.shape[1]}")

print("\n--- Метод info() (Типы данных и пропуски) ---")
df.info()

print("\n--- Метод describe() (Статистика числовых полей) ---")
display(df.describe())

--- Метод head(3) (Первые 3 строки) ---

      Товар    Категория      Цена  Возраст_модели_мес  Гарантия_мес
0  Смартфон  Электроника   50000.0                  12            24
1   Ноутбук   Компьютеры  120000.0                   6            12
2   Планшет  Электроника   35000.0                  18            12

--- Метод tail(2) (Последние 2 строки) ---

     Товар   Категория      Цена  Возраст_модели_мес  Гарантия_мес
6  Ноутбук  Компьютеры  120000.0                   6            12
7  Монитор  Компьютеры       NaN                  10            12

--- Свойство shape (Размерность) ---
Строк: 8, Столбцов: 5

--- Метод info() (Типы данных и пропуски) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Товар               8 non-null      object
 1   Категория           8 non-null      object
 2   Цена                7 non-null      float64
 3   Возраст_модели_мес  8 non-null      int64
 4   Гарантия_мес        8 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 452.0+ bytes

--- Метод describe() (Статистика числовых полей) ---

                Цена  Возраст_модели_мес  Гарантия_мес
count       7.000000             8.00000      8.000000
mean    67142.857143            11.37500     17.250000
std     41013.934914             6.90626      9.852483
min     15000.000000             3.00000      6.000000
25%     42500.000000             6.00000     12.000000
50%     50000.000000            11.00000     12.000000
75%    100000.000000            13.50000     24.000000
max    120000.000000            24.00000     36.000000

In [ ]:
print("--- Расчет пропущенных значений (NaN) ---")
missing_count = df.isna().sum().sort_values(ascending=False)
missing_percent = (df.isna().mean() * 100).sort_values(ascending=False)

display(pd.DataFrame({'Кол-во NaN': missing_count, 'Процент %': missing_percent}))

# Логическое заполнение пропусков: заполняем пустую цену средней ценой компьютеров
df['Цена'] = df['Цена'].fillna(df.groupby('Категория')['Цена'].transform('mean'))

print("\n--- Удаление дубликатов строк ---")
rows_before = df.shape[0]
duplicates_count = df.duplicated().sum()

# Удаляем дубликаты
df_cleaned = df.drop_duplicates().reset_index(drop=True)
rows_after = df_cleaned.shape[0]

print(f"Количество строк до удаления: {rows_before}")
print(f"Найдено строк-дубликатов: {duplicates_count}")
print(f"Количество строк после удаления: {rows_after}")

print("\nОчищенный DataFrame:")
display(df_cleaned)

--- Расчет пропущенных значений (NaN) ---

                    Кол-во NaN  Процент %
Цена                         1       12.5
Товар                        0        0.0
Категория                    0        0.0
Возраст_модели_мес           0        0.0
Гарантия_мес                 0        0.0

--- Удаление дубликатов строк ---
Количество строк до удаления: 8
Найдено строк-дубликатов: 2
Количество строк после удаления: 6

Очищенный DataFrame:

       Товар    Категория      Цена  Возраст_модели_мес  Гарантия_мес
0   Смартфон  Электроника   50000.0                  12            24
1    Ноутбук   Компьютеры  120000.0                   6            12
2    Планшет  Электроника   35000.0                  18            12
3   Наушники        Аудио   15000.0                   3             6
4  Телевизор  Электроника   80000.0                  24            36
5    Монитор   Компьютеры  120000.0                  10            12

In [ ]:
print("--- Фильтрация через query() (Цена > 40000) ---")
display(df_cleaned.query('Цена > 40000'))

print("\n--- Выборка через loc[] (Строки 0-2, столбцы 'Товар' и 'Цена') ---")
display(df_cleaned.loc[0:2, ['Товар', 'Цена']])

print("\n--- Выборка через iloc[] (Строки 0-2, столбцы 0-1) ---")
display(df_cleaned.iloc[0:3, 0:2])

print("\n--- Векторизованная работа с Datetime ---")
# Добавляем колонку с датами поставок (пока в виде строк)
df_cleaned['Дата_поставки'] = ['2025-01-15', '2025-11-20', '2024-06-10', '2026-02-01', '2025-08-14', '2023-12-25']

# Переводим в формат datetime
df_cleaned['Дата_поставки'] = pd.to_datetime(df_cleaned['Дата_поставки'])

# Считаем разницу в днях относительно сегодняшней даты
today = pd.to_datetime('today')
df_cleaned['Дней_с_момента_поставки'] = (today - df_cleaned['Дата_поставки']).dt.days

# Извлекаем отдельные составляющие даты в новые колонки
df_cleaned['Год'] = df_cleaned['Дата_поставки'].dt.year
df_cleaned['День'] = df_cleaned['Дата_поставки'].dt.day
df_cleaned['Месяц'] = df_cleaned['Дата_поставки'].dt.month

display(df_cleaned)

--- Фильтрация через query() (Цена > 40000) ---

       Товар    Категория      Цена  Возраст_модели_мес  Гарантия_мес
0   Смартфон  Электроника   50000.0                  12            24
1    Ноутбук   Компьютеры  120000.0                   6            12
4  Телевизор  Электроника   80000.0                  24            36
5    Монитор   Компьютеры  120000.0                  10            12

--- Выборка через loc[] (Строки 0-2, столбцы 'Товар' и 'Цена') ---

      Товар      Цена
0  Смартфон   50000.0
1   Ноутбук  120000.0
2   Планшет   35000.0

--- Выборка через iloc[] (Строки 0-2, столбцы 0-1) ---

      Товар    Категория
0  Смартфон  Электроника
1   Ноутбук   Компьютеры
2   Планшет  Электроника

--- Векторизованная работа с Datetime ---

,Товар,Категория,Цена,Возраст_модели_мес,Гарантия_мес,Дата_поставки,Дней_с_момента_поставки,Год,День,Месяц
0,Смартфон,Электроника,50000.0,12,24,2025-01-15,488,2025,15,1
1,Ноутбук,Компьютеры,120000.0,6,12,2025-11-20,179,2025,20,11
2,Планшет,Электроника,35000.0,18,12,2024-06-10,707,2024,10,6
3,Наушники,Аудио,15000.0,3,6,2026-02-01,106,2026,1,2
4,Телевизор,Электроника,80000.0,24,36,2025-08-14,277,2025,14,8
5,Монитор,Компьютеры,120000.0,10,12,2023-12-25,875,2023,25,12